(defvar *eq-items/wiki-buffer-name* "eq-items/wiki/")
(defvar *eq-items/ahungry-wtb-buffer-name* "eq-items/ahungry/buyers/")
(defvar *eq-items/ahungry-wts-buffer-name* "eq-items/ahungry/sellers/")

(defun eq-items/wiki (item-name)
  (setq *eq-items/wiki-buffer-name* (concat "*eq-items/wiki/" item-name "*"))
  (require 'shr)
  (url-retrieve
   (concat "http://wiki.project1999.com/"
           (replace-regexp-in-string " " "_" item-name))
   (lambda (&optional status cbargs)
     (let ((markup (current-buffer)))
       (delete-region (point-min) (1+ url-http-end-of-headers))
       (shr-render-buffer markup)
       (rename-buffer *eq-items/wiki-buffer-name*)
       (kill-buffer markup)))))

(defun eq-items/ahungry-wtb (item-name)
  (setq *eq-items/ahungry-wtb-buffer-name* (concat "*eq-items/ahungry/buyers/" item-name "*"))
  (require 'shr)
  (url-retrieve
   (concat "http://ahungry.com/action/eq/getItems/wtb/"
           (replace-regexp-in-string " " "+" item-name))
   (lambda (&optional status cbargs)
     (let ((markup (current-buffer)))
       (delete-region (point-min) (1+ url-http-end-of-headers))
       (shr-render-buffer markup)
       (rename-buffer *eq-items/ahungry-wtb-buffer-name*)
       (kill-buffer markup)))))

(defun eq-items/ahungry-wts (item-name)
  (setq *eq-items/ahungry-wts-buffer-name* (concat "*eq-items/ahungry/sellers/" item-name "*"))
  (require 'shr)
  (url-retrieve
   (concat "http://ahungry.com/action/eq/getItems/wts/"
           (replace-regexp-in-string " " "+" item-name))
   (lambda (&optional status cbargs)
     (let ((markup (current-buffer)))
       (delete-region (point-min) (1+ url-http-end-of-headers))
       (shr-render-buffer markup)
       (rename-buffer *eq-items/ahungry-wts-buffer-name*)
       (kill-buffer markup)))))

(defun eq-items/caller (item-name)
  (eq-items/wiki item-name)
  (eq-items/ahungry-wtb item-name)
  (eq-items/ahungry-wts item-name))

(defvar eq-item/candidates
  (list "10 Dose Ant's Potion"
        "10 Dose Blood of the Wolf"
        "10 Dose Ethira's Poison Antidote"
        "10 Dose Greater Null Potion"
        "10 Dose Greater Potion of Purity"
        "10 Dose Kilva's Skin of Flame"
        "10 Dose Kithar's Disease Treatment"
        "10 Dose Null Potion"
        "10 Dose Potion of Antiweight"
        "10 Dose Potion of Aquatic Haunt"
        "10 Dose Potion of Heat"
        "10 Dose Potion of Power"
        "10 Dose Potion of Purity"
        "10 Dose Potion of Stability"
        "10 Dose Potion of the Frost"
        "10 Dose Potion of the Swamp"
        "10 Dose Potion of Unlife Awareness"
        "10 Dose Vial of Tamed Mercury"
        "10 Doses of Greater Power"
        "5 Dose Blood of the Wolf"
        "5 Dose Potion of the Swamp"
        "5 Dose Potion of Unlife Awareness"
        "Abalone Gorget"
        "Acid Etched War Sword"
        "Adamantite Armband"
        "Adamantite Band"
        "Adamantite Bo Stick"
        "Adamantite Club"
        "Adamantite Epaulets"
        "Adamantium Bands"
        "Adumbrate Globe"
        "Advisor Robe"
        "Alligator Tooth Earring"
        "Amanita Phalloide"
        "Amber"
        "Amethyst Bracelet"
        "Amulet of Necropotence"
        "Ancient Coin"
        "Ancient Coin"
        "Ancient Coin"
        "Ancient Coin"
        "Ancient Coin"
        "Ancient Coin"
        "Ancient Shissar Gauntlet"
        "Ant's Potion"
        "Antonian Javelin"
        "Apothic Sleeves"
        "Arbitor's Combine Greatsword"
        "Archeologist Pack"
        "Argent Defender"
        "Ashenwood Short Spear"
        "Asp Poison Sac"
        "Atramentous Shield"
        "Auburn Tessera"
        "Augmentor's Gem"
        "Aviak Charm"
        "Aviak Eggs"
        "Axe of Lost Souls"
        "Axe of the Iron Back"
        "Axe of the Slayers"
        "Azure Sleeves"
        "Backpack"
        "Backpack"
        "Bag of Caynar Nuts"
        "Bag of the Tinkerers"
        "Bamboo Bo Stick"
        "Band of Eternal Flame"
        "Band of Flesh"
        "Banded Belt"
        "Banded Boots"
        "Banded Bracer"
        "Banded Cloak"
        "Banded Gauntlets"
        "Banded Gorget"
        "Banded Helm"
        "Banded Leggings"
        "Banded Mail"
        "Banded Mantle"
        "Banded Mask"
        "Banded Sleeves"
        "Bandoleer of Luclin"
        "Barbarian Hunting Spear"
        "Barbarian Meat"
        "Barbed Armplates"
        "Barbed Leather Whip"
        "Barbed Legplates"
        "Barbed Scale Whip"
        "Bargynn's Torch"
        "Bark Shield"
        "Barnacle Breastplate"
        "Basilisk Eggs"
        "Bat Wing"
        "Batfang Headband"
        "Baton of Faith"
        "Batskull Earring"
        "Battle Staff"
        "Beaded Slime Necklace"
        "Bear Meat"
        "Beartooth Necklace"
        "Beer Braised Lion"
        "Beer Braised Wolf"
        "Beetle stinger"
        "Belt"
        "Belt of Contention"
        "Belt of Flesh Hooks"
        "Belt of the Cenobite"
        "Berries"
        "Bixie Stinger"
        "Bixie Stinger"
        "Black Chitin Leggings"
        "Black Fine Plate Breastplate"
        "Black Fine Plate Greaves"
        "Black Griffon Feather"
        "Black Headband"
        "Black Iron Girdle"
        "Black Iron Medallion"
        "Black Pearl"
        "Black Pearl Electrum Choker"
        "Black Pearl Electrum Choker"
        "Black Pearl Platinum Ring"
        "Black Pearl Platinum Ring"
        "Black Sapphire"
        "Black Sapphire Electrum Earring"
        "Black Sapphire Electrum Earring"
        "Black Sapphire Platinum Necklace"
        "Black Sapphire Platinum Necklace"
        "Black Silk Gloves"
        "Black Tome with Silver Runes"
        "Black Wolf Skin"
        "Blackburrow Cask"
        "Blackburrow Gnoll Skin"
        "Blackened Iron Armplates"
        "Blackened Iron Bastard Sword"
        "Blackened Iron Boots"
        "Blackened Iron Coif"
        "Blackened Iron Collar"
        "Blackened Iron Eye Totem"
        "Blackened Iron Gloves"
        "Blackened Iron Legplates"
        "Blackened Iron Mail"
        "Blackened Sapphire"
        "Blackened Teir'Dal"
        "Blackened Wand"
        "Blackjack"
        "Blade of Fiery Lamentations"
        "Blade of Passage"
        "Blade of the Black Dragon Eye"
        "Blade of the Earthcaller"
        "Blade of the Green Dragon Eye"
        "Blade of Xalgoz"
        "Bladed Thulian Claws"
        "Bladestopper"
        "Blighted Robe"
        "Block of High Quality Ore"
        "Block of Permafrost"
        "Blockcutter Gloves"
        "Blood Ember Boots"
        "Blood Ember Bracer"
        "Blood Ember Breastplate"
        "Blood Ember Gauntlets"
        "Blood Ember Greaves"
        "Blood Ember Helm"
        "Blood Ember Vambraces"
        "Blood Fire"
        "Blood Fork"
        "Blood of the Dhampyre"
        "Blood of the Wolf"
        "Blood Point"
        "Blood Soaked Plasmatic Priest Robe"
        "Blood Temper"
        "Bloodforge Bracers"
        "Bloodforge Hammer"
        "Bloodforge Helm"
        "Bloodstained Gloves"
        "Bloodstained Mantle"
        "Bloodstained Tunic"
        "Bloodstone Earring"
        "Bloodstone Eyepatch"
        "Bloodstone Ring"
        "Bloody Dirk"
        "Blue Crystal Staff"
        "Blue Diamond"
        "Bluish Stone"
        "Bo Stick"
        "Bone Amulet of Blade Turning"
        "Bone Armplates"
        "Bone Bladed Claymore"
        "Bone Chips"
        "Bone Chips"
        "Bone Chips"
        "Bone Chips"
        "Bone Chips"
        "Bone Chips"
        "Bone Chips"
        "Bone Chips"
        "Bone Chips"
        "Bone Fingered Gloves"
        "Bone Legplates"
        "Bone Mask of the Jarsath"
        "Bone Razor"
        "Bone Shield"
        "Bone Talisman"
        "Book of Obulus"
        "Book of Scale"
        "Book of the Rings"
        "Boots of Ro"
        "Boots of the Reliant"
        "Bottled Djinni"
        "Bottom of Broken Staff"
        "Box of Nil Space"
        "Bracelet of Beetlekind"
        "Bracelet of Exertion"
        "Bracelet of Woven Grass"
        "Bracer of Ro"
        "Bracer of Scavenging"
        "Bracer of the Hidden"
        "Bracer of Vajeen"
        "Bracers of Battle"
        "Bracers of Erollisi"
        "Bracers of the Reverent"
        "Braided Cinch Cord"
        "Braided Ivy Cords"
        "Brass Earring"
        "Brass Goblin Flamberge"
        "Brass Knuckles"
        "Brazen Brass Kilij"
        "Brazier of Elemental Summoning"
        "Breastplate"
        "Breastplate of Ro"
        "Breath of Harmony"
        "Breath of Ro"
        "Breath of Solusek"
        "Brell's Girdle"
        "Brell's Keg Popper"
        "Brigandine Tunic"
        "Bronze Boots"
        "Bronze Bracers"
        "Bronze Breastplate"
        "Bronze Collar"
        "Bronze Gauntlets"
        "Bronze Girdle"
        "Bronze Greaves"
        "Bronze Helm"
        "Bronze Pauldron"
        "Bronze Vambraces"
        "Broom"
        "Brown Chitin Protector"
        "Brownie Parts"
        "Brutechopper"
        "Bunch of Optic Nerves"
        "Burning Rapier"
        "Burnished Wooden Stave"
        "Burnt Wood Staff"
        "Burynai Digmaster's Claw"
        "Burynai Hide Boots"
        "Burynai Hide Bracelets"
        "Burynai Hide Cap"
        "Burynai Hide Choker"
        "Burynai Hide Cloak"
        "Burynai Hide Gloves"
        "Burynai Hide Mask"
        "Burynai Hide Pants"
        "Burynai Hide Shoulder Pads"
        "Burynai Hide Sleeves"
        "Burynai Hide Tunic"
        "Burynai Legion Gi"
        "Burynaibane Charm"
        "Burynaibane Spider Fang"
        "Butler Syncalls Fang"
        "Cabilis Scale Leggings"
        "Cane of Harmony"
        "Cane of the Tranquil"
        "Cape of Midnight Mist"
        "Carnal Pauldrons"
        "Carnelian"
        "Carrion Beetle Leggings"
        "Carved Elm Recurve Bow"
        "Carved Elm Recurve Bow"
        "Carved Elm Recurve Bow"
        "Carved Ivory Mask"
        "Cat Eye Platinum Necklace"
        "Cat Eye Platinum Necklace"
        "Cat o' Nine Tails"
        "Cat's Eye Agate"
        "Ceremonial Iksar Chestplate"
        "Charcoal"
        "Charred Boots"
        "Charred Gauntlets"
        "Charred Guardian Breastplate"
        "Charred Guardian Shield"
        "Charred Tulwar"
        "Chestplate of the Constant"
        "Chestplate of the Dark Flame"
        "Chieftain's Headress"
        "Child's Tear"
        "Chipped Bone Bracelet"
        "Chipped Bone Collar"
        "Chipped Bone Rod"
        "Chitin Shell Armor"
        "Chitin Shell Shield"
        "Choker of Majdd"
        "Chromodrac Gut"
        "Chrysoberyl Talisman"
        "Cinnamon Sticks"
        "Circlet of Shadow"
        "CLASS 4 Bone Hooked Arrow"
        "CLASS 4 Bone Hooked Arrow"
        "CLASS 4 Bone Hooked Arrow"
        "Clay Guardian Shield"
        "Clay Totem"
        "Cloak of Flames"
        "Cloak of Leaves"
        "Cloak of Shadows"
        "Cloak of the Ice Bear"
        "Cloak of the Undead Eye"
        "Clockwork Oil Stout"
        "Cloth Cape"
        "Club"
        "Cobalt Boots"
        "Cobalt Bracer"
        "Cobalt Breastplate"
        "Cobalt Gauntlets"
        "Cobalt Greaves"
        "Cobalt Helm"
        "Cobalt Vambraces"
        "Cold Iron Morning Star"
        "Collar of Undead Protection"
        "Compass"
        "Cone of the Mystics"
        "Copper Ring"
        "Cracked Darkwood Shield"
        "Cracked Leather Belt"
        "Crafted Bracers"
        "Crafted Breastplate"
        "Crafted Gauntlets"
        "Crafted Greaves"
        "Crafted Helm"
        "Crafted Pauldron"
        "Crafted Plate Boots"
        "Crafted Vambraces"
        "Crested Helm"
        "Crested Mistmoore Shield"
        "Crested Spaulders"
        "Crimson Robe of Alendine"
        "Crimson Tessera"
        "Crookstinger"
        "Crown of Elemental Mastery"
        "Crown of King Tranix"
        "Crown of Leaves"
        "Crown of the Froglok Kings"
        "Crude Stein"
        "Crushbone Belt"
        "Crushbone Shoulderpads"
        "Cryosilk Webshield"
        "Cryptrobber's Knife"
        "Crystalline Blade"
        "Crystalline Orb"
        "Crystalline Short Sword"
        "Crystalline Spear"
        "Crystallized Pumice"
        "Crystallized Sulfur"
        "Cured Silk Cloak"
        "Cured Silk Collar"
        "Cured Silk Gi"
        "Cured Silk Handwraps"
        "Cured Silk Headband"
        "Cured Silk Leggings"
        "Cured Silk Mask"
        "Cured Silk Sandals"
        "Cured Silk Sash"
        "Cured Silk Sleeves"
        "Cured Silk Wristbands"
        "Cutthroat Insignia Ring"
        "Cyclops Eye"
        "Cyclops skull"
        "Cyclops Toes"
        "Dagger"
        "Dagger of Dropping"
        "Dagger of Frost"
        "Dagger of Marnek"
        "Damask Robe"
        "Damask Sash"
        "Dareb's Skull"
        "Dark Boned Bracelet"
        "Dark Circlet"
        "Dark Elf Parts"
        "Dark Mail Gauntlets"
        "Dark Reaver"
        "Dark Rust Boots"
        "Dark Rust Bracer"
        "Dark Scale Greaves"
        "Dark Yellow Fine Plate Helm"
        "Darkforge Boots"
        "Darkforge Bracer"
        "Darkforge Breastplate"
        "Darkforge Gauntlets"
        "Darkforge Greaves"
        "Darkforge Helm"
        "Darkforge Vambraces"
        "Darksea Harpoon"
        "Darkwood Staff"
        "Deadwood Stave"
        "Death Scarab Gland"
        "Deathbringer's Rod"
        "Deathfist Pawn Scalp"
        "Deathfist Shoulderpads"
        "Deathfist Slashed Belt"
        "Deathwatch Sword"
        "Decree of Quellious"
        "Deepwater Boots"
        "Deepwater Bracer"
        "Deepwater Breastplate"
        "Deepwater Gauntlets"
        "Deepwater Greaves"
        "Deepwater Harpoon"
        "Deepwater Helm"
        "Deepwater Vambraces"
        "Dented Brass Mask"
        "Devlas Ilkvel"
        "Diamond"
        "Diamond Electrum Mask"
        "Diamond Electrum Mask"
        "Diamond Encrusted Staff"
        "Diamondine Earring"
        "Diaphanous Globe"
        "Djarns Amethyst Ring"
        "Djinni Statuette"
        "Donal's Boots of Mourning"
        "Donal's Bracer of Mourning"
        "Donal's Chestplate of Mourning"
        "Donal's Gauntlets of Mourning"
        "Donal's Helm of Mourning"
        "Donal's Vambraces of Mourning"
        "Drachnid Leg Tip"
        "Drachnid Thyxl"
        "Dragon Bone Bracelet"
        "Dragon Hero Bracer"
        "Dragon Horn Ykesha"
        "Dragon Scales"
        "Dragon Scales"
        "Dragon Scales"
        "Dragoon Dirk"
        "Drake Fang"
        "Drakescale Belt"
        "Dreadscale Boots"
        "Dreadscale Bracer"
        "Dreadscale Breastplate"
        "Dreadscale Gauntlets"
        "Dreadscale Greaves"
        "Dreadscale Helm"
        "Dreadscale Mask"
        "Dreadscale Vambraces"
        "Dried Leather"
        "Drogan Obsidian Dagger"
        "Drolvarg Mantle"
        "Drop of Mercury"
        "Dufrenite"
        "Dustscryer's Crystal Ball"
        "Dusty Bloodstained Gloves"
        "Dusty Breastplate"
        "Dusty Burlap Sack"
        "Dusty Rusted Vambraces"
        "Dwarf Meat"
        "Dwarven Axe"
        "Dwarven Axe"
        "Dwarven Blood"
        "Dwarven Plate Boots"
        "Dwarven Plate Boots"
        "Dwarven Plate Bracers"
        "Dwarven Plate Bracers"
        "Dwarven Plate Breastplate"
        "Dwarven Plate Breastplate"
        "Dwarven Plate Collar"
        "Dwarven Plate Collar"
        "Dwarven Plate Gauntlets"
        "Dwarven Plate Gauntlets"
        "Dwarven Plate Girdle"
        "Dwarven Plate Girdle"
        "Dwarven Plate Greaves"
        "Dwarven Plate Greaves"
        "Dwarven Plate Helm"
        "Dwarven Plate Helm"
        "Dwarven Plate Vambraces"
        "Dwarven Plate Vambraces"
        "Dwarven Plate Visor"
        "Dwarven Plate Visor"
        "Dwarven Ringmail Tunic"
        "Dwarven Sap"
        "Dwarven Splinted Cloak"
        "Dwarven Splinted Cloak"
        "Dwarven Work Boots"
        "Earring of Disease Reflection"
        "Earring of Essence"
        "Earring of Fire Reflection"
        "Earring of Frost Reflection"
        "Earring of Magic Reflection"
        "Earring of Poison Reflection"
        "Earthen Blade"
        "Earthen Temper"
        "Earthshaker"
        "Ebon Mace"
        "Ebon Razor"
        "Ebon Tessera"
        "Ebon War Spear"
        "Ebonwood Cudgel"
        "Ebony Bladed Sword"
        "Edge of Cabilis"
        "Edge of the Nightwalker"
        "Efreeti Battle Axe"
        "Efreeti Statuette"
        "Efreeti War Axe"
        "Efreeti War Bow"
        "Efreeti Zweihander"
        "Elder Spiritist's Boots"
        "Elder Spiritist's Bracer"
        "Elder Spiritist's Breastplate"
        "Elder Spiritist's Gauntlets"
        "Elder Spiritist's Greaves"
        "Elder Spiritist's Helm"
        "Elder Spiritist's Vambraces"
        "Electrum Bloodstone Necklace"
        "Electrum Bloodstone Necklace"
        "Electrum Bracelet"
        "Electrum Carnelian Wedding Ring"
        "Electrum Carnelian Wedding Ring"
        "Electrum Cat Eye Bracelet"
        "Electrum Cat Eye Bracelet"
        "Electrum Fire Wedding Ring"
        "Electrum Fire Wedding Ring"
        "Electrum Jasper Earring"
        "Electrum Jasper Earring"
        "Electrum Opal Amulet"
        "Electrum Opal Amulet"
        "Electrum Star Amulet"
        "Electrum Star Amulet"
        "Electrum Star Ruby Ring"
        "Electrum Star Ruby Ring"
        "Elliptical Veil"
        "Elven Blood"
        "Elven Veal"
        "Embroidered Black Cape"
        "Embroidered Black Sleeves"
        "Emerald"
        "Emerald"
        "Emerald Spiroc Feather"
        "Enameled Black Chestplate"
        "Enameled Black Mace"
        "Enchanted Dwarven Breastplate"
        "Enchanted Dwarven Plate Boots"
        "Enchanted Dwarven Plate Bracers"
        "Enchanted Dwarven Plate Collar"
        "Enchanted Dwarven Plate Gauntlets"
        "Enchanted Dwarven Plate Greaves"
        "Enchanted Dwarven Plate Helm"
        "Enchanted Dwarven Plate Pauldron"
        "Enchanted Dwarven Plate Vambraces"
        "Enchanted Dwarven Plate Visor"
        "Enchanted Dwarven Splinted Cloak"
        "Enchanted Elven Chain Mantle"
        "Enchanted Fine Steel Morning Star"
        "Enchanted Full Breastplate"
        "Enchanted Full Breastplate"
        "Enchanted Full Breastplate"
        "Enchanted Full Breastplate"
        "Enchanted Full Plate Boots"
        "Enchanted Full Plate Boots"
        "Enchanted Full Plate Boots"
        "Enchanted Full Plate Boots"
        "Enchanted Full Plate Bracers"
        "Enchanted Full Plate Bracers"
        "Enchanted Full Plate Bracers"
        "Enchanted Full Plate Bracers"
        "Enchanted Full Plate Greaves"
        "Enchanted Full Plate Greaves"
        "Enchanted Full Plate Greaves"
        "Enchanted Full Plate Greaves"
        "Enchanted Full Plate Helm"
        "Enchanted Full Plate Helm"
        "Enchanted Full Plate Helm"
        "Enchanted Full Plate Helm"
        "Enshrouded Veil"
        "Envy"
        "Erudite Meat"
        "Essence Emerald"
        "Essence of Dol"
        "Essence of Moonlight"
        "Essence of Rathe"
        "Essence of Shadow"
        "Essence of Sunlight"
        "Essence of Winter"
        "Etched Ivory Charm"
        "Ethereal Amber"
        "Ethereal Opal"
        "Evergreen Leaf"
        "Evil Eye Lens"
        "Executioners Hood"
        "Eye of Innoruuk"
        "Eye of Melnor"
        "Eye of Serilis"
        "Eye of Shadow"
        "Faintly Glowing Diamond"
        "Fairy Dust"
        "Fang Amulet of Calling"
        "Fang of the Wolf"
        "Farsight Crystal"
        "Faydark Ringmail Coat"
        "Feathered Leggings"
        "Felhammer"
        "Festering Cloak"
        "Field Plate Bracers"
        "Fighting Baton"
        "Filleting Knife"
        "Fine Plate Boots"
        "Fine Plate Breastplate"
        "Fine Plate Collar"
        "Fine Plate Gauntlets"
        "Fine Plate Greaves"
        "Fine Plate Helm"
        "Fine Plate Vambraces"
        "Fine Silk Turban"
        "Fine Steel Dagger"
        "Fine Steel Great Staff"
        "Fine Steel Long Sword"
        "Fine Steel Scimitar"
        "Fine Steel Short Sword"
        "Finely Woven Cloth Amice"
        "Finely Woven Gold Mesh"
        "Fingerbone Hoop"
        "Fire Beetle Eye"
        "Fire Crystal Staff"
        "Fire Drake Scale"
        "Fire Emerald"
        "Fire Emerald Electrum Bracelet"
        "Fire Emerald Electrum Bracelet"
        "Fire Emerald Golden Bracelet"
        "Fire Emerald Golden Bracelet"
        "Fire Emerald Platinum Ring"
        "Fire Emerald Platinum Ring"
        "Fire Giant Toes"
        "Fire Opal"
        "Firerune Brand"
        "Fish Rolls"
        "Fish Scales"
        "Fishbone Earring"
        "Fishbone Necklace"
        "Fist of Zek"
        "Flame of Vox"
        "Flaming Sword of Xuzl"
        "Flawless Aquamarine"
        "Flayed Skin Boots"
        "Flayed Skin Bracers"
        "Flayed Skin Cap"
        "Flayed Skin Leggings"
        "Flayed Skin Sleeves"
        "Flayed Skin Tunic"
        "Flayed Turmoilskin Belt"
        "Fleeting Quiver"
        "Flowing Black Robe"
        "Flowing Black Silk Sash"
        "Foreman's Tunic"
        "Forest Loop"
        "Froglok Blood"
        "Froglok Bonecaster's Robe"
        "Froglok Scale Chestplate"
        "Froglok Skin Mask"
        "Frost Crystal"
        "Frost Temper"
        "Frothy Goblin Tonic"
        "Fruit"
        "Fungi Covered Great Staff"
        "Fungus Covered Scale Tunic"
        "Fur Lined Mask"
        "Gargantuan Tarantula Heart"
        "Gargantuan Tarantula Leg"
        "Gargoyle Eye"
        "Gatorscale Leggings"
        "Gatorscale Sleeves"
        "Gatorsmash Maul"
        "Gauntlets of Brute Strength"
        "Gauntlets of Fiery Might"
        "Gauntlets of Potence"
        "Gauntlets of Ro"
        "Gauntlets of the Ardent"
        "Gear"
        "Gem Encrusted Circlet"
        "Gem Encrusted Ring"
        "Gem Finder"
        "Gem Inlaid Gauntlets"
        "Gem of Empowerment"
        "Gem of Invigoration"
        "Ghostly Robes"
        "Ghoulbane"
        "Giant Fire Beetle Leg"
        "Giant Foreman's Tunic"
        "Giant Lord's Tunic"
        "Giant Sized Monocle"
        "Giant Snake Fang"
        "Giant Snake Rattle"
        "Giant Snakespine Belt"
        "Giants Reminder String"
        "Gigantic Zweihander"
        "Gilded Cloth"
        "Girdle of the Diligent"
        "Gladius"
        "Glaive of Marltek"
        "Gleaming Short Sword"
        "Glob of Gooey Goo"
        "Gloomwater Harpoon"
        "Glove of Rallos Zek"
        "Glowing Black Stone"
        "Glowing Bone Collar"
        "Glowing Club"
        "Glowing Iron Pike"
        "Glowing Stone Band"
        "Glowing Torch"
        "Glowing Wooden Crook"
        "Gnoll Hide Lariat"
        "Gnoll Hide Tome"
        "Gnome Kabobs"
        "Gnome Meat"
        "Gnomish Environment Suit"
        "Goblin Backstabber"
        "Goblin Choker"
        "Goblin Forged Chainmail Coat"
        "Goblin Forged Chainmail Gloves"
        "Goblin Forged Chainmail Neckguard"
        "Goblin Forged Iron Armplates"
        "Goblin Forged Iron Mask"
        "Goblin Gazughi Ring"
        "Goblin Head"
        "Goblin Parrying Dagger"
        "Goblin Parrying Spear"
        "Goblin Skull Crusher"
        "Goblin Soul Caller"
        "Goblin Spirit Catcher"
        "Gold Bloodstone Necklace"
        "Gold Bloodstone Necklace"
        "Gold Carnelian Wedding Ring"
        "Gold Carnelian Wedding Ring"
        "Gold Malachite Bracelet"
        "Gold Malachite Bracelet"
        "Gold Nugget"
        "Gold Nugget"
        "Gold Nugget"
        "Gold Plated Koshigatana"
        "Gold Ring"
        "Gold Ring"
        "Gold Turquoise Engagement Ring"
        "Gold Turquoise Engagement Ring"
        "Golden Amber Earring"
        "Golden Amber Earring"
        "Golden Black Pearl Choker"
        "Golden Black Pearl Choker"
        "Golden Black Sapphire Earring"
        "Golden Black Sapphire Earring"
        "Golden Bracer"
        "Golden Bracer"
        "Golden Cat Eye Bracelet"
        "Golden Cat Eye Bracelet"
        "Golden Chitin Bracer"
        "Golden Diamond Mask"
        "Golden Diamond Mask"
        "Golden Ear Stud"
        "Golden Efreeti Boots"
        "Golden Fire Wedding Ring"
        "Golden Fire Wedding Ring"
        "Golden Jacinth Wedding Ring"
        "Golden Jacinth Wedding Ring"
        "Golden Jaded Bracelet"
        "Golden Jaded Bracelet"
        "Golden Locket"
        "Golden Locket"
        "Golden Opal Amulet"
        "Golden Opal Amulet"
        "Golden Pearl Choker"
        "Golden Pearl Choker"
        "Golden Ruby Ring"
        "Golden Ruby Ring"
        "Golden Sapphire Earring"
        "Golden Sapphire Earring"
        "Golden Star Amulet"
        "Golden Star Amulet"
        "Golden Star Ruby Ring"
        "Golden Star Ruby Ring"
        "Golden Topaz Earring"
        "Golden Topaz Earring"
        "Golem Metal Wand"
        "Golem Tear Ring"
        "Gorilla Hide Leggings"
        "Gorilla Hide Mask"
        "Gossamer Leggings"
        "Gossamer Robe"
        "Granite Bracer"
        "Granite Earring"
        "Granite Face Grinder"
        "Grave Sandals"
        "Gravebinder"
        "Greater Lightstone"
        "Greater Null Potion"
        "Greaves of Ro"
        "Greaves of the Penitent"
        "Green Dragon Scales"
        "Green Jade Axe"
        "Green Jade Broadsword"
        "Green Jade Halberd"
        "Green Silken Drape"
        "Greenwood Bo Stick"
        "Grey Fur Cape"
        "Gridelin Globe"
        "Griffenne Blood"
        "Griffon Eggs"
        "Griffon Eye"
        "Griffon Feathers"
        "Griffon Talon Gloves"
        "Griffon Wing"
        "Grizzly Bear Skin"
        "Gromlok's Basher"
        "Grotesque Mask"
        "Guardians Mace"
        "Gypsy Lute"
        "Gypsy Medallion"
        "Halfling Parts"
        "Hammer of Flattening"
        "Hammerhead Helm"
        "Hand Made Backpack"
        "Hand of the Reaper"
        "Hand Woven Leggings"
        "Hand Woven Shoulder Guards"
        "Hardened Clay"
        "Hardened Clay Bracelet"
        "Harmonic Dagger"
        "Harpoon of the Depths"
        "Harpy Tongue"
        "Harvester"
        "Head of Ghanex Drah"
        "Head of Shen"
        "Head of the Valiant"
        "Heady Kiola"
        "Heart of Fire"
        "Helm of Brute Strength"
        "Helm of Rile"
        "Helm of Ro"
        "Helot Skull Helm"
        "Hematite"
        "Hero Bracers"
        "Hexed Kerran Doll"
        "Hierophant's Cloak"
        "Hierophant's Cloak"
        "High Elf Parts"
        "High Quality Bear Skin"
        "High Quality Bear Skin"
        "High Quality Cat Pelt"
        "High Quality Lion Skin"
        "High Quality Wolf Skin"
        "Hill Giant Toes"
        "Hollow Bone Shank"
        "Hollowed Bone Bracers"
        "Honeycomb"
        "Hooded Black Cloak"
        "Hopper Spear"
        "Horn"
        "Howling Harpoon"
        "Hulking Spiked Club"
        "Human Blood"
        "Human Parts"
        "Hyaline Globe"
        "Ice Crystal Staff"
        "Ice Giant Toes"
        "Ice Goblin Blood"
        "Ice of Velious"
        "Icy Blade"
        "Idol of the Thorned"
        "Idol of the Underking"
        "Iksar Berserker Club"
        "Iksar Blood"
        "Iksar Hide Boots"
        "Iksar Hide Mask"
        "Iksar Scaled Gloves"
        "Iksar Skin Gloves"
        "Iksar Skull with an 'X'"
        "Iksar Skull with an 'X'"
        "Iksar Targ Shield"
        "Illegible Scroll"
        "Illegible Scroll"
        "Illegible Scroll"
        "Illegible Scroll"
        "Illegible Scroll"
        "Illegible Scroll"
        "Illegible Scroll"
        "Imbued Cabilis Scale Cap"
        "Imbued Cabilis Scale Cape"
        "Imbued Cabilis Scale Leggings"
        "Imbued Dwarven Plate Helm"
        "Imbued Elven Chain Cape"
        "Imbued Elven Chain Coif"
        "Imbued Elven Chain Tunic"
        "Imbued Elven Chainmail Boots"
        "Imbued Elven Chainmail Bracelet"
        "Imbued Elven Chainmail Gloves"
        "Imbued Elven Chainmail Leggings"
        "Imbued Elven Chainmail Skirt"
        "Imbued Elven Chainmail Sleeves"
        "Imbued Field Breastplate"
        "Imbued Field Breastplate"
        "Imbued Field Breastplate"
        "Imbued Field Breastplate"
        "Imbued Field Breastplate"
        "Imbued Field Breastplate"
        "Imbued Field Breastplate"
        "Imbued Field Plate Boots"
        "Imbued Field Plate Boots"
        "Imbued Field Plate Boots"
        "Imbued Field Plate Boots"
        "Imbued Field Plate Boots"
        "Imbued Field Plate Boots"
        "Imbued Field Plate Boots"
        "Imbued Field Plate Bracers"
        "Imbued Field Plate Bracers"
        "Imbued Field Plate Bracers"
        "Imbued Field Plate Bracers"
        "Imbued Field Plate Bracers"
        "Imbued Field Plate Bracers"
        "Imbued Field Plate Bracers"
        "Imbued Field Plate Collar"
        "Imbued Field Plate Collar"
        "Imbued Field Plate Collar"
        "Imbued Field Plate Collar"
        "Imbued Field Plate Collar"
        "Imbued Field Plate Collar"
        "Imbued Field Plate Collar"
        "Imbued Field Plate Gauntlets"
        "Imbued Field Plate Gauntlets"
        "Imbued Field Plate Gauntlets"
        "Imbued Field Plate Gauntlets"
        "Imbued Field Plate Gauntlets"
        "Imbued Field Plate Gauntlets"
        "Imbued Field Plate Gauntlets"
        "Imbued Field Plate Girdle"
        "Imbued Field Plate Girdle"
        "Imbued Field Plate Girdle"
        "Imbued Field Plate Girdle"
        "Imbued Field Plate Girdle"
        "Imbued Field Plate Girdle"
        "Imbued Field Plate Girdle"
        "Imbued Field Plate Greaves"
        "Imbued Field Plate Greaves"
        "Imbued Field Plate Greaves"
        "Imbued Field Plate Greaves"
        "Imbued Field Plate Greaves"
        "Imbued Field Plate Greaves"
        "Imbued Field Plate Greaves"
        "Imbued Field Plate Helm"
        "Imbued Field Plate Helm"
        "Imbued Field Plate Helm"
        "Imbued Field Plate Helm"
        "Imbued Field Plate Helm"
        "Imbued Field Plate Helm"
        "Imbued Field Plate Helm"
        "Imbued Field Plate Pauldron"
        "Imbued Field Plate Pauldron"
        "Imbued Field Plate Pauldron"
        "Imbued Field Plate Pauldron"
        "Imbued Field Plate Pauldron"
        "Imbued Field Plate Pauldron"
        "Imbued Field Plate Pauldron"
        "Imbued Field Plate Vambraces"
        "Imbued Field Plate Vambraces"
        "Imbued Field Plate Vambraces"
        "Imbued Field Plate Vambraces"
        "Imbued Field Plate Vambraces"
        "Imbued Field Plate Vambraces"
        "Imbued Field Plate Vambraces"
        "Imbued Fighters Staff"
        "Imbued Granite Spauldors"
        "Imbued Jade"
        "Imbued Mithril Reinforced Cloak"
        "Imbued Mithril Reinforced Leggings"
        "Imbued Mithril Studded Leggings"
        "Imbued Mithril Studded Mask"
        "Imbued Ogre War Boots"
        "Imbued Ogre War Boots"
        "Imbued Ogre War Bracer"
        "Imbued Ogre War Bracer"
        "Imbued Ogre War Breastplate"
        "Imbued Ogre War Breastplate"
        "Imbued Ogre War Cloak"
        "Imbued Ogre War Cloak"
        "Imbued Ogre War Gauntlets"
        "Imbued Ogre War Gauntlets"
        "Imbued Ogre War Greaves"
        "Imbued Ogre War Greaves"
        "Imbued Ogre War Helm"
        "Imbued Ogre War Helm"
        "Imbued Ogre War Pauldron"
        "Imbued Ogre War Pauldron"
        "Imbued Ogre War Vambraces"
        "Imbued Ogre War Vambraces"
        "Imbued Ogre War Visor"
        "Imbued Ogre War Visor"
        "Imbued Platinum Fire Ring"
        "Imbued Shield of Paineel"
        "Imbued Vale Reinforced Leggings"
        "Imbued Vale Studded Gorget"
        "Imbued Vale Studded Leggings"
        "Imbued Vale Studded Mask"
        "Immortals"
        "Imp Statuette"
        "Impskin Gloves"
        "Incandescent Gloves"
        "Incandescent Mask"
        "Incarnadine Boots"
        "Incarnadine Breastplate"
        "Incarnadine Greaves"
        "Incarnadine Helm"
        "Insignia Protector"
        "Intestine Necklace"
        "Iron Bound Tome"
        "Iron Disc"
        "Iron Leash Collar"
        "Iron Oxide"
        "Ivandyr's Hoop"
        "Ivory Bracelet"
        "Ivory Imbued Collar"
        "Ivory Pendant"
        "Ivy Etched Boots"
        "Ivy Etched Bracer"
        "Ivy Etched Helm"
        "Ivy Etched Leggings"
        "Ivy Etched Sleeves"
        "Ivy Etched Tunic"
        "Jacinth"
        "Jade"
        "Jade Chokidai Prod"
        "Jade Chokidai Prod"
        "Jade Inlaid Coffin"
        "Jade Inlaid Crescent Axe"
        "Jade Mace"
        "Jade Reaver"
        "Jade Shard"
        "Jaded Electrum Bracelet"
        "Jaded Electrum Bracelet"
        "Jaded Platinum Ring"
        "Jaded Platinum Ring"
        "Jaded Silver Ring"
        "Jaded Silver Ring"
        "Jagged Band"
        "Jagged Blade of Mourning"
        "Jagged Chokidai Spine"
        "Jagged Diamond Dagger"
        "Jagged Long Sword"
        "Jagged Metal Shard"
        "Jaggedpine Crook"
        "Jambiya"
        "Jarsath Battle Sword"
        "Jarsath Trident"
        "Jasper"
        "Jasper Gold Earring"
        "Jasper Gold Earring"
        "Jaundiced Bone Boots"
        "Jaundiced Bone Bracer"
        "Jaundiced Bone Gauntlets"
        "Jaundiced Bone Greaves"
        "Jaundiced Bone Helm"
        "Jaundiced Bone Vambraces"
        "Jeweled Skull"
        "Jeweled Skull"
        "Journeyman's Boots"
        "Journeyman's Walking Stick"
        "Kejaar Totem"
        "Kerran Tribal Headband"
        "Ketchata Koro Mis"
        "Key to Charasis"
        "Kicsh Der Pavz"
        "Kilij Plans"
        "Kiola Nut"
        "Knobbed Warclub"
        "Knuckle Dusters"
        "Kunzar Cloak"
        "Kunzar Hex Amulet"
        "Kunzar Ku'juch"
        "Kylong Arm Guards"
        "Kylong Boots"
        "Kylong Gauntlets"
        "Kylong Greaves"
        "Kylong War Dagger"
        "Kylong War Helm"
        "Kylong Wrist Guards"
        "Labyrinth Talisman"
        "Lambent Boots"
        "Lambent Bracers"
        "Lambent Breastplate"
        "Lambent Gauntlets"
        "Lambent Greaves"
        "Lambent Helm"
        "Lambent Stone"
        "Lambent Vambraces"
        "Lamentation"
        "Lamentation Blade"
        "Langseax"
        "Langseax of the Wolves"
        "Large Banded Belt"
        "Large Banded Boots"
        "Large Banded Bracer"
        "Large Banded Cloak"
        "Large Banded Gauntlets"
        "Large Banded Gorget"
        "Large Banded Helm"
        "Large Banded Leggings"
        "Large Banded Mail"
        "Large Banded Mantle"
        "Large Banded Mask"
        "Large Banded Sleeves"
        "Large Brick of High Quality Ore"
        "Large Bronze Boots"
        "Large Bronze Bracers"
        "Large Bronze Breastplate"
        "Large Bronze Gauntlets"
        "Large Bronze Greaves"
        "Large Bronze Helm"
        "Large Bronze Pauldron"
        "Large Bronze Vambraces"
        "Large Brown Rust Fine Breastplate"
        "Large Fine Plate Collar"
        "Large Fine Plate Helm"
        "Large Fine Plate Visor"
        "Large Fine Steel Breastplate"
        "Large Leather Leggings"
        "Large Leather Skullcap"
        "Large Leather Tunic"
        "Large Ornate Chain Bracelet"
        "Large Ornate Chain Coif"
        "Large Ornate Chain Gloves"
        "Large Ornate Chain Sleeves"
        "Large Ornate Chain Veil"
        "Large Red Fine Plate Bracer"
        "Large Red Fine Plate Vambraces"
        "Large Ringmail Bracelet"
        "Large Ringmail Coat"
        "Large Ringmail Gloves"
        "Large Ringmail Pants"
        "Large Sewing Kit"
        "Large Soiled Bag"
        "Large Splinted Bronze Cloak"
        "Large Studded Cloak"
        "Larrikan's Mask"
        "Lasnik's Staff"
        "Lava Potion"
        "Lava Rock"
        "Leather Padding"
        "Leatherfoot Raider Skullcap"
        "Leatherfoot Raider Skullcap"
        "Leatherfoot Raider Skullcap"
        "Leering Mask"
        "Left Goblin Ear"
        "Leg"
        "Legionnaire's Bracer"
        "Lexicon"
        "Lexicon"
        "Light Burlap Sack"
        "Lightstone"
        "Lionhide Backpack"
        "Lizard Blood Potion"
        "Lizardscale Belt"
        "Lizardscale Cloak"
        "Lizardscale Mantle"
        "Lizardskin Tribal Mask"
        "Loam Encrusted Amice"
        "Loam Encrusted Bracelet"
        "Loam Encrusted Cap"
        "Loam Encrusted Choker"
        "Loam Encrusted Cloak"
        "Loam Encrusted Gloves"
        "Loam Encrusted Lined Shoes"
        "Loam Encrusted Pantaloons"
        "Loam Encrusted Robe"
        "Loam Encrusted Sash"
        "Loam Encrusted Sleeves"
        "Loam Encrusted Veil"
        "Locket of Escape"
        "Lockjaw Hide Vest"
        "Lockpicks"
        "Locustlure"
        "Longbow"
        "Lost Staff of the Scorned"
        "Low Quality Bear Skin"
        "Low Quality Cat Pelt"
        "Low Quality Lion Skin"
        "Low Quality Wolf Skin"
        "Lrg Ornate Electrum Chain Bracelet"
        "Lumberjack's Cap"
        "Luminary Two Handed Sword"
        "Luminescent Staff"
        "Lupine Claw Gauntlets"
        "Lupine Dagger"
        "Lupine Runed Armband"
        "Lute"
        "Lute of the Gypsy Princess"
        "Mace"
        "Mace of the Shadowed Soul"
        "Maid Issis Fang"
        "Malachite"
        "Mallet Head"
        "Mallet Hilt"
        "Mammoth Hide Cloak"
        "Mammoth Hide Leggings"
        "Mammoth Meat"
        "Mana Robe"
        "Manastone"
        "Mandolin"
        "Mandolin"
        "Mantle of Mirth"
        "Marauder Snout Ring 'MM'"
        "Margyl's Tongue"
        "Marr Cherries"
        "Marr's Promise"
        "Mask of Deception"
        "Mask of Obtenebration"
        "Mask of Shadow"
        "Mask of the Eight Eyes"
        "Mask of Wurms"
        "Master Wu's Trance Stick"
        "Mechanized Lockpicks"
        "Medallion of the Jarsath"
        "Medallion of the Kylong"
        "Medallion of the Obulus"
        "Medicine Bag"
        "Medicine Totem"
        "Medium Quality Bear Skin"
        "Medium Quality Cat Pelt"
        "Medium Quality Wolf Skin"
        "Melatite"
        "Melodious Truncheon"
        "Mermaid Scale"
        "Mesh Bracers"
        "Mesh Cape"
        "Mesh Gauntlets"
        "Mesh Girth"
        "Mesh Helm"
        "Mesh Leggings"
        "Mesh Mantle"
        "Mesh Tunic"
        "Metal Pipe"
        "Metal Pipe"
        "Midnight Mallet"
        "Minotaur Battle Axe"
        "Minotaur Horn"
        "Minotaur Ribcage"
        "Mistmoore Battle Drums"
        "Misty Acorn"
        "Mithril Breastplate"
        "Mithril Disc"
        "Mithril Feir'Dal Dagger"
        "Mithril Feir'Dal Dagger"
        "Mithril Feir'Dal Dagger"
        "Mithril Frog Totem"
        "Mithril Greaves"
        "Mithril Plated Girth"
        "Mithril Quill"
        "Mithril Staff"
        "Mithril Vambraces"
        "Molten Cloak"
        "Moonlight Temper"
        "Moonstone Ring"
        "Morning Dew"
        "Mortificator Staff"
        "Moss Mask"
        "Mosscovered Twig"
        "Mottled Spiroc Feather"
        "Mountain Death Belt"
        "Mrylokar's Boots"
        "Mrylokar's Bracer"
        "Mrylokar's Breastplate"
        "Mrylokar's Gauntlets"
        "Mrylokar's Gift"
        "Mrylokar's Greaves"
        "Mrylokar's Helm"
        "Mrylokar's Vambraces"
        "Mucilaginous Girdle"
        "Mud Crabs"
        "Muddite Mud"
        "Mudman Enforcer"
        "Muffin Tin"
        "Mug of Sea Foam"
        "Mystical Claws of Jojo"
        "Nathsar Greatsword"
        "Nature's Wrath"
        "Necklace"
        "Necklace of Defiance"
        "Necklace of Superiority"
        "Necklace of the Tranquil"
        "Nightmare Hide"
        "Nightshade Wreath"
        "Noble's Robes"
        "Noctivagant Blade"
        "Nostrolo Tambourine"
        "Oak Bark"
        "Obsidian Bead Hoop"
        "Obsidian Ring"
        "Obsidian Ring of Quintessence"
        "Obsidian Scimitar"
        "Obsidian Shard"
        "Obsidian Shard"
        "Obtenebrate Short Sword"
        "Obulus Death Shroud"
        "Ochre Tessera"
        "Oggok Cleaver"
        "Ogre Butcher Gloves"
        "Ogre War Maul"
        "Onyx Drake Gut"
        "Onyx Drakescale Cloak"
        "Onyx Earring"
        "Opal"
        "Opalline Earring"
        "Opoline Helm"
        "Orange Headband"
        "Orb of Slime"
        "Orb of Tishan"
        "Orc Scalp"
        "Ornate Chain Gorget"
        "Ornate Electrum Chain Gloves"
        "Ornate Electrum Chain Mail"
        "Ornate Rune Blade"
        "Ornate Rune Shield"
        "Paineel Steel Vambraces"
        "Pair of Bent Spectacles"
        "Palladium Axe"
        "Patch of Shadow"
        "Patched Gnoll Fur Bundle"
        "Paw of Opolla"
        "Peacebringer"
        "Pearl Kedge Totem"
        "Pearl Ring"
        "Pearl Shard"
        "Pearlescent Mask"
        "Pegasus Feather Cloak"
        "Pegasus Statuette"
        "Pelt"
        "Peridot"
        "Petrified Bark Leggings"
        "Petrified Erudite Heart Amulet"
        "Petrified Redwood"
        "Phosphoric Globe"
        "Pie Tin"
        "Piece of a medallion"
        "Piece of a medallion"
        "Piece of a medallion"
        "Piece of a medallion"
        "Piece of a medallion"
        "Piece of a medallion"
        "Piece of a medallion"
        "Piece of a medallion"
        "Piece of a medallion"
        "Pixie Dust"
        "Pixie Powder Cinnesticks"
        "Plains Pebble"
        "Platinum Amber Ring"
        "Platinum Amber Ring"
        "Platinum Armband"
        "Platinum Bloodstone Earring"
        "Platinum Bloodstone Earring"
        "Platinum Carnelian Wedding Ring"
        "Platinum Carnelian Wedding Ring"
        "Platinum Diamond Wedding Ring"
        "Platinum Diamond Wedding Ring"
        "Platinum Disc"
        "Platinum Dragon Totem"
        "Platinum Fire Wedding Ring"
        "Platinum Fire Wedding Ring"
        "Platinum Jacinth Wedding Ring"
        "Platinum Jacinth Wedding Ring"
        "Platinum Jasper Ring"
        "Platinum Jasper Ring"
        "Platinum Onyx Bracelet"
        "Platinum Onyx Bracelet"
        "Platinum Opal Engagement Ring"
        "Platinum Opal Engagement Ring"
        "Platinum Pearl Ring"
        "Platinum Pearl Ring"
        "Platinum Ring"
        "Platinum Ruby Veil"
        "Platinum Ruby Veil"
        "Platinum Skull Ring"
        "Platinum Star Ruby Veil"
        "Platinum Star Ruby Veil"
        "Platinum Tiara"
        "Poison Wind Censer"
        "Polar Bear Skin"
        "Polished Bone Bracelet"
        "Polished Bone Hoop"
        "Polished Granite Tomahawk"
        "Polished Mithril Mask"
        "Polished Obsidian Great Axe"
        "Polished Stone Anklet"
        "Polyphenomenal Axe"
        "Pot"
        "Potion"
        "Potion of Insight"
        "Potion of Poison Warding"
        "Potion of Serious Healing"
        "Potion of the Frost"
        "Potion of the Swamp"
        "Potion of Unlife Awareness"
        "Pouch of Quellious"
        "Powered Gloves"
        "Prayer Cloth of Tunare"
        "Prayer Shawl"
        "Preserved Split Paw Eye"
        "Prickly Pear"
        "Pristine Giant Scarab Carapace"
        "Pugius"
        "Puppet Strings"
        "Purity Belt"
        "Purple Headband"
        "Qeynos Kite Shield"
        "Quiver"
        "Quiver of Marr"
        "Radiant Meteorite"
        "Ragebringer"
        "Rain Caller"
        "Rapier"
        "Rapier of Oriin"
        "Rat Ear Pie"
        "Rat Ear Pie"
        "Rat Shaped Ring"
        "Ration"
        "Ravener Tail Whip"
        "Ravenscale Armguards"
        "Ravenscale Belt"
        "Ravenscale Boots"
        "Ravenscale Bracer"
        "Ravenscale Chestguard"
        "Ravenscale Cloak"
        "Ravenscale Coif"
        "Ravenscale Gloves"
        "Ravenscale Leggings"
        "Ravenscale Mask"
        "Ravenscale Neckguard"
        "Ravenscale Shoulderpads"
        "Raw Silk Cloak"
        "Raw Silk Leggings"
        "Raw Silk Mantle"
        "Raw Silk Robe"
        "Raw Silk Sleeves"
        "Reaper of the Dead"
        "Rebreather"
        "Red Dragon Scales"
        "Red Dragon Tooth"
        "Red Dragonscale Armor"
        "Red Fine Plate Breastplate"
        "Red Headband"
        "Red Headband"
        "Red Sash of Order"
        "Red Wood Wand"
        "Reed Belt"
        "Reinforced Mask"
        "Reinforced Rhino Leggings"
        "Rile's Sand Coin"
        "Ring of Dominance"
        "Ring of Goblin Lords"
        "Ring of Shadows"
        "Ring of Slime"
        "Ring of the Ancients"
        "Ring of the Dead"
        "Ring of the Dead"
        "Ring of the Rockchanters"
        "Ring of the Stonechanters"
        "Ringed Mace of the Ykesha"
        "Ringmail Bracelet"
        "Ringmail Coat"
        "Ringmail Coif"
        "Ringmail Mantle"
        "Ringmail Sleeves"
        "Riptide Spear"
        "Robe of Dalnir"
        "Robe of Enshroudment"
        "Robe of Living Fungus"
        "Robe of the Azure Sky"
        "Robe of the Elements"
        "Robe of the Foci"
        "Robe of the Ishva"
        "Robe of the Kedge"
        "Robe of the Keeper"
        "Robe of the Lost Circle"
        "Robe of the Oracle"
        "Robe of the Oracle"
        "Robe of the Spring"
        "Robe of the Whistling Fists"
        "Rod of Annihilation"
        "Rod of Faith"
        "Rod of Identification"
        "Rod of Insidious Glamour"
        "Rod of Lamentation"
        "Rod of Mourning"
        "Rod of Oblations"
        "Rokyls Channelling Crystal"
        "Ropy Tendril"
        "Rose Platinum Engagement Ring"
        "Rose Platinum Engagement Ring"
        "Rotbone Bracelet"
        "Rotwood Club"
        "Rough Ashwood Recurve Bow"
        "Rough Ashwood Recurve Bow"
        "Rough Ashwood Recurve Bow"
        "Rough Darkwood Recurve Bow"
        "Rough Darkwood Recurve Bow"
        "Rough Darkwood Recurve Bow"
        "Rough Hickory Recurve Bow"
        "Rough Hickory Recurve Bow"
        "Rough Hickory Recurve Bow"
        "Rubicite Boots"
        "Rubicite Breastplate"
        "Rubicite Greaves"
        "Rubicite Helm"
        "Ruby"
        "Ruby"
        "Ruby Electrum Ring"
        "Ruby Electrum Ring"
        "Ruined Scaled Boots"
        "Ruined Scaled Bracelet"
        "Ruined Scaled Coat"
        "Ruined Scaled Sleeves"
        "Ruined Wolf Pelt"
        "RukGus' Sticker"
        "Rune of Al'Kabor"
        "Rune of Attraction"
        "Rune of Attraction"
        "Rune of Banding"
        "Rune of Conception"
        "Rune of Concussion"
        "Rune of Consumption"
        "Rune of Contortion"
        "Rune of Crippling"
        "Rune of Disassociation"
        "Rune of Embrace"
        "Rune of Expulsion"
        "Rune of Falhalem"
        "Rune of Frost"
        "Rune of Frost"
        "Rune of Fulguration"
        "Rune of Fulguration"
        "Rune of Howling"
        "Rune of Impetus"
        "Rune of Karana"
        "Rune of Karana"
        "Rune of Nagafen"
        "Rune of Neglect"
        "Rune of Oppression"
        "Rune of Petrification"
        "Rune of Presence"
        "Rune of Proximity"
        "Rune of Proximity"
        "Rune of Rallos Zek"
        "Rune of Rathe"
        "Rune of Regeneration"
        "Rune of Substance"
        "Rune of the Astral"
        "Rune of the Astral"
        "Rune of the Catalyst"
        "Rune of the Cyclone"
        "Rune of the Helix"
        "Rune of Trauma"
        "Rune of Velious"
        "Rune of Xegony"
        "Runebranded Girdle"
        "Runed Blade"
        "Runed Bolster Belt"
        "Runed Bone Fork"
        "Runed Circlet"
        "Runed Cowl"
        "Runed Falchion"
        "Runed Fighters Staff"
        "Runed Lava Pendant"
        "Runed Mithril Bracer"
        "Runed Morning Star"
        "Runed Oak Bow"
        "Runed Totem Staff"
        "Runewood Great Staff"
        "Runic Carver"
        "Russet Oxide"
        "Rusty Dagger"
        "Rusty Dagger"
        "Rusty Shortened Spear"
        "Rusty Spiked Shoulderpads"
        "Sabertooth Amulet"
        "Sabertooth Tiger Mane"
        "Sacrificial Dagger"
        "Sage's Battle Staff"
        "Sainy's Claw"
        "Sainy's Singing Dagger"
        "Salindrite Dagger"
        "Saltwater Seaweed"
        "Sand of Ro"
        "Sap of Piety"
        "Sapphire"
        "Sapphire"
        "Sapphire Electrum Earring"
        "Sapphire Electrum Earring"
        "Sapphire Platinum Necklace"
        "Sapphire Platinum Necklace"
        "Sarcoscypha Fungus"
        "Sarnak Arcane Fetish"
        "Sarnak Battle Shield"
        "Sarnak Battlehammer"
        "Sarnak Blood"
        "Sarnak Blood"
        "Sarnak Bracer of Honor"
        "Sarnak Ceremonial Dagger"
        "Sarnak Ceremonial Sword"
        "Sarnak Eitchatka"
        "Sarnak Emblazened Tabard"
        "Sarnak Enforcer"
        "Sarnak Flesh Harvester"
        "Sarnak Great Cleaver"
        "Sarnak Headguard"
        "Sarnak Hide Girdle"
        "Sarnak Liberator"
        "Sarnak Parrying Blade"
        "Sarnak Pitchatka"
        "Sarnak Skullsplitter"
        "Sarnak Warhammer"
        "Sash of the Dragonborn"
        "Sathir's Wand"
        "Savant's Cap"
        "Scaled Mystic Bracers"
        "Scaled Mystic Breastplate"
        "Scaled Mystic Cloak"
        "Scaled Mystic Gauntlets"
        "Scaled Mystic Greaves"
        "Scaled Mystic Helm"
        "Scaled Mystic Vambraces"
        "Scaled Prowler Belt"
        "Scarab Ring"
        "Scepter of Flame"
        "Scepter of Rahotep"
        "Scimitar of the Mistwalker"
        "Scimitar of the Ykesha"
        "Scorched Pauldrons"
        "Scorpikis Claw Impaler"
        "Scorpion Meat"
        "Scourgetail Bracer"
        "Scourgetail Whip"
        "Screaming Mace"
        "Scute Shield"
        "Seahorse Scale Cloak"
        "Sebilite Croaking Dirk"
        "Sebilite Scale Belt"
        "Sebilite Scale Boots"
        "Sebilite Scale Bracelet"
        "Sebilite Scale Cap"
        "Sebilite Scale Cape"
        "Sebilite Scale Coat"
        "Sebilite Scale Gloves"
        "Sebilite Scale Leggings"
        "Sebilite Scale Mantle"
        "Sebilite Scale Mask"
        "Sebilite Scale Neckguard"
        "Sebilite Scale Vambraces"
        "Serpent Insignia Collar"
        "Serpent's Tooth"
        "Serpentine Bracer"
        "Serpentwood Staff"
        "Serrated Bone Dirk"
        "Severed Paw"
        "Shadow Silk"
        "Shadow Temper"
        "Shadow Wolf Pelt"
        "ShadowBound Boots"
        "ShadowBound Gloves"
        "Shadowed Ball"
        "Shadowed Book"
        "Shadowed Halberd"
        "Shadowed Rapier"
        "Shadowed Scythe"
        "Shaped Ashwood Recurve Bow"
        "Shaped Ashwood Recurve Bow"
        "Shaped Ashwood Recurve Bow"
        "Shard of Darkness"
        "Shardwing Arrow"
        "Shark Meat"
        "Shark Skin"
        "Shark Skin"
        "Shark Tooth"
        "Sharkbone Warhammer"
        "Sharkjaw Cutlass"
        "Sharkskin Drum"
        "Shazda Turban"
        "Sheer Bone Mask"
        "Shield of Kurn"
        "Shield of Prexus"
        "Shield of Rainbow Hues"
        "Shield of Spectral Essence"
        "Shield of the Immaculate"
        "Shield of the Red Dragon"
        "Shield of the Slain Unicorn"
        "Shield of the Stalwart Seas"
        "Shield of the Water Dragon"
        "Shield of the White Dragon"
        "Shieldstorm"
        "Shimmering Amber"
        "Shimmering Diamond"
        "Shimmering Opal"
        "Shimmering Orb"
        "Shimmering Partisan"
        "Shimmering White Shroud"
        "Shining Metallic Robes"
        "Shiny Brass Halberd"
        "Shiny Brass Idol"
        "Shiny Brass Shield"
        "Shiny Golden Coin"
        "Shiny Robe of the Underfoot"
        "Shissar Nullifier Staff"
        "Short Sword"
        "Short Sword"
        "Short Sword of the Ykesha"
        "Shovel"
        "Shovel"
        "Shralok Pack"
        "Shroud of Nature"
        "Shrunken Goblin Skull Earring"
        "Shuriken of the Tranquil"
        "Siblisian Berserker Cloak"
        "Silk Swatch"
        "Silk Thread"
        "Silken Whip of Ensnaring"
        "Silver Amber Ring"
        "Silver Amber Ring"
        "Silver Bloodstone Earring"
        "Silver Bloodstone Earring"
        "Silver Bracelet"
        "Silver Carnelian Wedding Ring"
        "Silver Carnelian Wedding Ring"
        "Silver Cat Eye Necklace"
        "Silver Cat Eye Necklace"
        "Silver Etched Warhammer"
        "Silver Fire Wedding Ring"
        "Silver Fire Wedding Ring"
        "Silver Hematite Ring"
        "Silver Hematite Ring"
        "Silver Jasper Ring"
        "Silver Jasper Ring"
        "Silver Mesh"
        "Silver Onyx Bracelet"
        "Silver Onyx Bracelet"
        "Silver Opal Engagement Ring"
        "Silver Opal Engagement Ring"
        "Silver Ring"
        "Silver Ring"
        "Silver Ring"
        "Silver Ring"
        "Silver Rose Engagement Ring"
        "Silver Rose Engagement Ring"
        "Silver Ruby Veil"
        "Silver Ruby Veil"
        "Silver Swiftblade"
        "Silvered Sapphire Necklace"
        "Silvered Sapphire Necklace"
        "Silvered Star Ruby Veil"
        "Silvered Star Ruby Veil"
        "Silverish Scimitar"
        "Silversilk Leggings"
        "Silvery Girdle"
        "Silvery Two Handed Axe"
        "Silvery War Axe"
        "Singed Scroll"
        "Singing Steel Boots"
        "Singing Steel Bracer"
        "Singing Steel Breastplate"
        "Singing Steel Gauntlets"
        "Singing Steel Greaves"
        "Singing Steel Helm"
        "Singing Steel Vambraces"
        "Sionachie's Partisan"
        "Siren Scale Robe"
        "Siryn Hair Hood"
        "Skinning Knife"
        "Skull"
        "Skullchip Bracelet"
        "Skullhelm of Krenlek"
        "Sky Pearl"
        "Slime Blood of Cazic Thule"
        "Slime Coated Harpoon"
        "Slime Crystal Staff"
        "Slithinis's Shield"
        "Slowstone Amber"
        "Sludged Girdle"
        "Small Banded Belt"
        "Small Banded Boots"
        "Small Banded Bracer"
        "Small Banded Cloak"
        "Small Banded Gauntlets"
        "Small Banded Helm"
        "Small Banded Leggings"
        "Small Banded Mail"
        "Small Banded Mantle"
        "Small Banded Mask"
        "Small Banded Sleeves"
        "Small Bronze Boots"
        "Small Bronze Bracers"
        "Small Bronze Breastplate"
        "Small Bronze Collar"
        "Small Bronze Gauntlets"
        "Small Bronze Girdle"
        "Small Bronze Greaves"
        "Small Bronze Helm"
        "Small Bronze Mask"
        "Small Bronze Pauldron"
        "Small Bronze Vambraces"
        "Small Crafted Bracers"
        "Small Crafted Breastplate"
        "Small Crafted Gauntlets"
        "Small Crafted Greaves"
        "Small Crafted Helm"
        "Small Crafted Plate Boots"
        "Small Crafted Vambraces"
        "Small Fine Plate Boots"
        "Small Fine Plate Gauntlets"
        "Small Fine Plate Greaves"
        "Small Fine Plate Helm"
        "Small Fine Steel Breastplate"
        "Small Patchwork Cloak"
        "Small Pick"
        "Small Reinforced Mask"
        "Small Ringmail Cape"
        "Small Ringmail Coat"
        "Small Ringmail Coif"
        "Small Ringmail Gloves"
        "Small Ringmail Neckguard"
        "Small Ringmail Pants"
        "Small Ringmail Sleeves"
        "Small Scarab Boots"
        "Small Scarab Breastplate"
        "Small Scarab Helm"
        "Small Splinted Bronze Cloak"
        "Small Studded Belt"
        "Small Studded Boots"
        "Small Studded Leggings"
        "Small Wisdom Deity"
        "Smoked Wood Elf"
        "Smokey Quartz Dagger"
        "Smoldering Brand"
        "Snake Scales"
        "Snakeskin Gloves"
        "Snakeskin Jerkin"
        "Solist's Icy Wand"
        "Solvedi Scimitar"
        "Songbird Statuette"
        "Soul Binder"
        "Sparring Clogs"
        "Spear"
        "Spear of Mortification"
        "Spectral Shroud"
        "Sphinx Heart Amulet"
        "Spider Silk"
        "Spider Venom Sac"
        "Spiderling Eye"
        "Spiderling Silk"
        "Spiked Collar"
        "Spiked Goblin Ring"
        "Spine Piercer"
        "Spined Dragon Claws"
        "Spirit Tome"
        "Spiroc Bone Dust"
        "Spiroc Feathers"
        "Spiroc Statuette"
        "Spiroc Talon"
        "Splinted Bronze Cloak"
        "Split Paw Hide Belt"
        "Split Paw Hide Gloves"
        "Split Paw Hide Mask"
        "Split Paw Hide Tunic"
        "Split Paw Tooth Necklace"
        "Sporali Gloves"
        "Springwood Club"
        "Springwood Stave"
        "Spyglass"
        "Squallsurge Shawl"
        "Staff"
        "Staff of Battle"
        "Staff of Forbidden Rites"
        "Staff of the Dreaded Gaze"
        "Staff of the Earthcrafter"
        "Staff of the Observers"
        "Staff of the Waterwalker"
        "Staff of Undead Legions"
        "Staff of Writhing"
        "Stalking Probe"
        "Star Rose Quartz"
        "Star Ruby"
        "Stave of Shielding"
        "Steel Boning"
        "Steel Hilted Flint Dagger"
        "Stein"
        "Stein"
        "Stein"
        "Stein of Moggok"
        "Stein of Moggok"
        "Stein of Tears"
        "Stiletto of the Bloodclaw"
        "Stone Circlet"
        "Stone of Morid"
        "Stormwood Battle Staff"
        "Strange Ochre Clay"
        "Strathbone Shell Shield"
        "Straw Spun Belt"
        "Studded Boots"
        "Studded Leather Collar"
        "Studded Skullcap"
        "Studs"
        "Succulent Sap"
        "Superb Wolf Hide"
        "Supple Scale Armband"
        "Swarmcaller"
        "Swirling Mist"
        "Sword of Skyfire"
        "Sword of the Morning"
        "Sylvan Berries"
        "Symbol of Loyalty to Vox"
        "Symphonic Saber"
        "Syythrak Hide Vest"
        "Tailored Large Bag"
        "Tailored Quiver"
        "Tainted Battleworn Morning Star"
        "Tattered Arm Wrappings"
        "Tattered Gnomish Cloak"
        "Tattered Leg Wrappings"
        "Tattered Mantle"
        "Tattered Tomb Shroud"
        "Tea Leaves"
        "Tears of Prexus"
        "Tentacle Whip"
        "Terrorantula Silk"
        "Tesch Val Sinisch"
        "Thaumaturgist's Robe"
        "The Scent of Marr"
        "Thex Dagger"
        "Thex Mallet"
        "Thick Banded Belt"
        "Thick Grizzly Bear Skin"
        "Thick Leather Apron"
        "Thorny Blackjack"
        "Throneblade of the Ykesha"
        "Throwing Boulder"
        "Tiger Hide Gloves"
        "Tiger Skin"
        "Tobrin's Mystical Eyepatch"
        "Tolan's Darkwood Boots"
        "Tolan's Darkwood Bracer"
        "Tolan's Darkwood Breastplate"
        "Tolan's Darkwood Gauntlets"
        "Tolan's Darkwood Greaves"
        "Tolan's Darkwood Helm"
        "Tolan's Darkwood Vambraces"
        "Tolapumj's Robe"
        "Tombcarver"
        "Tome of Miragul"
        "Tome of Order and Discord"
        "Tome of the Eternal"
        "Toolbox"
        "Topaz Silver Necklace"
        "Topaz Silver Necklace"
        "Topknot Headband"
        "Torch"
        "Torch"
        "Totem of the Warrior Spirit"
        "Totemic Boots"
        "Totemic Bracers"
        "Totemic Breastplate"
        "Totemic Cloak"
        "Totemic Gauntlets"
        "Totemic Greaves"
        "Totemic Helm"
        "Totemic Vambraces"
        "Tower Guard's Blade"
        "Trakanasaur Hide Gloves"
        "Trakanasaur Hide Leggings"
        "Trakanasaur Hide Sleeves"
        "Trakanasaur Hide Tunic"
        "Trakanon Idol"
        "Trakasaur's Tooth"
        "Tranquil Staff"
        "Travelers Pack"
        "Treant Staff"
        "Tree Weave"
        "Troll Parts"
        "Trooper Scale Bracers"
        "Trooper Scale Breastplate"
        "Trooper Scale Gauntlets"
        "Trooper Scale Greaves"
        "Trooper Scale Helm"
        "Trooper Scale Vambraces"
        "Trueshot Longbow"
        "Truesilver Mail Bracelets"
        "Truesilver Mail Coif"
        "Truncheon of Doom"
        "Turquoise"
        "Turquoise Eyepatch"
        "Turtleshell Helm"
        "Twisted Bone Earring"
        "Two Handed Practice Sword"
        "Unicorn Horn"
        "Unicorn Horn"
        "Unicorn Horn"
        "Used Merchants Gloves"
        "Vale Reinforced Mask"
        "Valorium Boots"
        "Valorium Gauntlets"
        "Valorium Greaves"
        "Vambraces of Ro"
        "Vambraces of the Fervent"
        "Vegetables"
        "Velvet Choker"
        "Vial of Egg Whites"
        "Vial of Swirling Smoke"
        "Vial of Vampire Blood"
        "Vial of Viscous Mana"
        "Vibrating Gauntlets of Infuse"
        "Viik's Dark Defender"
        "Vineclinger Berries"
        "Wand of Allure"
        "Wand of Conflagration"
        "Wand of Frost Bolts"
        "Wand of Lava"
        "Wand of Swords"
        "Warding Star"
        "Watchman Boots"
        "Water Crystal Staff"
        "Water Sprinkler of Nem Ankh"
        "Water Sprinkler of the Forgiven"
        "Waters of Impenetrable Aura"
        "Weight of the Gods"
        "Werewolf Claws"
        "Werewolf Pelt"
        "Werewolf Skin Cloak"
        "Whip of Strangulation"
        "Whirling Agate"
        "Whirling Bloodstone"
        "Whirling Hematite"
        "Whirling Lapis Lazuli"
        "Whirling Turquoise"
        "White Dragon Scales"
        "White Dragon Tooth"
        "White Dragonscale Cloak"
        "White Gold Necklace"
        "White Headband"
        "White Spiroc Feather"
        "White Training Sash"
        "White Wolf Skin"
        "Whore's Bane"
        "Wild One Wig"
        "Wilder's Girdle"
        "Windetched Staff"
        "Windruned Dagger"
        "Wing of Xegony"
        "Wintry Club"
        "Withered Leather Belt"
        "Withered Leather Boots"
        "Withered Leather Cloak"
        "Withered Leather Gloves"
        "Withered Leather Gorget"
        "Withered Leather Leggings"
        "Withered Leather Mask"
        "Withered Leather Shoulderpads"
        "Withered Leather Skullcap"
        "Withered Leather Sleeves"
        "Withered Leather Tunic"
        "Withered Leather Wristbands"
        "Withered Staff"
        "Withered Totem of Widdershins"
        "Woe"
        "Wolf Fur Slippers"
        "Wolf Meat"
        "Wolf's Eye Golden Bracelet"
        "Wolf's Eye Golden Bracelet"
        "Wolf's Eye Platinum Necklace"
        "Wolf's Eye Platinum Necklace"
        "Wood Elf Parts"
        "Woodsman's Staff"
        "Wooly Spider Silk Net"
        "Words of Abatement"
        "Words of Absorption"
        "Words of Allure"
        "Words of Anthology"
        "Words of Bidding"
        "Words of Bondage"
        "Words of Burnishing"
        "Words of Cloudburst"
        "Words of Coercion"
        "Words of Convocation"
        "Words of Dark Paths"
        "Words of Darkness"
        "Words of Derivation"
        "Words of Descrying"
        "Words of Detachment"
        "Words of Detention"
        "Words of Dimension"
        "Words of Discernment"
        "Words of Dissemination"
        "Words of Dissolution"
        "Words of Dominion"
        "Words of Dominion"
        "Words of Duration"
        "Words of Duress"
        "Words of Endurance"
        "Words of Enlightenment"
        "Words of Eradication"
        "Words of Grappling"
        "Words of Haunting"
        "Words of Imitation"
        "Words of Incarceration"
        "Words of Materials"
        "Words of Mistbreath"
        "Words of Motion"
        "Words of Neglect"
        "Words of Obligation"
        "Words of Odus"
        "Words of Parasitism"
        "Words of Possession"
        "Words of Projection"
        "Words of Purification"
        "Words of Quivering"
        "Words of Radiance"
        "Words of Recluse"
        "Words of Refuge"
        "Words of Requisition"
        "Words of Resolve"
        "Words of Reviviscence"
        "Words of Rupturing"
        "Words of Sight"
        "Words of Spirit"
        "Words of the Element"
        "Words of the Ethereal"
        "Words of the Extinct"
        "Words of the Psyche"
        "Words of the Quickening"
        "Words of the Spoken"
        "Words of the Suffering"
        "Words of Transcendence"
        "Words of Tyranny"
        "Worker Sledgemallet"
        "Worn Cloth Mantle"
        "Worn Crescent Axe"
        "Woven Cap"
        "Woven Cape"
        "Woven Girth"
        "Woven Gloves"
        "Woven Leggings"
        "Woven Mantle"
        "Woven Sleeves"
        "Woven Tunic"
        "Wraith Bone Hammer"
        "Wu's Fighting Gauntlets"
        "Wu's Quivering Staff"
        "Wurm Scale Coat"
        "Wurmslayer"
        "Xalgozian Fang"
        "Yellow Headband"
        "Ykeshan War Club"
        "Yun Shaman Powder"
        "Zaharn's Coronet"
        "Zealot's Incarnadine Sword"
        "Zombie Skin"
        ))

(defun eq-items/search-wiki ()
  (interactive)
  (helm :sources `((name . "Search for what item?")
                   (candidates . ,eq-item/candidates)
                   (action . eq-items/wiki)
                   (persistent-help . "Type an item name to look up prices on wiki."))
        :buffer "*eq items wiki search*"))

(defun eq-items/search-sellers ()
  (interactive)
  (helm :sources `((name . "Search for what item?")
                   (candidates . ,eq-item/candidates)
                   (action . eq-items/ahungry-wts)
                   (persistent-help . "Type an item name to look up who's selling it."))
        :buffer "*eq items seller search*"))

(defun eq-items/search-buyers ()
  (interactive)
  (helm :sources `((name . "Search for what item?")
                   (candidates . ,eq-item/candidates)
                   (action . eq-items/ahungry-wtb)
                   (persistent-help . "Type an item name to look up who's buying it."))
        :buffer "*eq items buyer search*"))

(defun eq-items/search-all ()
  (interactive)
  (helm :sources `((name . "Search for what item?")
                   (candidates . ,eq-item/candidates)
                   (action . eq-items/caller)
                   (persistent-help . "Type an item name to look up prices on wiki and sellers."))
        :buffer "*eq items search*"))

(provide 'eq-items)
